name: CI

on:
  push:
    branches:
      - develop
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          docker build -t mon_app .
          docker run mon_app npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push Docker image
        run: |
          docker tag mon_app:latest ${{ secrets.DOCKERHUB_USERNAME }}/mon_app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mon_app:latest

